### ISSUE TITLE
MapServer does not work, only FeatureServer work

### ISSUE THREAD

**Issue by hoogw** [rowanwins/arcgis-pbf-parser#1]
all sample use ESRI arcgis server v10.71 or v10.81,

however, f=pbf only works with FeatureServer, not MapServer. 

For details

[https://transparentgov.net/cleargov1/940/pbf-not-work-with-mapserver-but-work-with-featureserver](https://transparentgov.net/cleargov1/940/pbf-not-work-with-mapserver-but-work-with-featureserver)

Open your postman app, try sample:

v10.81 MapServer, not work, f=pbf, just same as f=json.

[https://gis.la-quinta.org/arcgis/rest/services/BaseMap/Parcel/MapServer/1/query?&resultOffset=0&resultRecordCount=500&returnGeometry=true&outSR=4326&f=pbf&outFields=*&geometryType=esriGeometryEnvelope&geometry=%7B%22spatialReference%22:%7B%22wkid%22:4326%7D,%20%22xmin%22%20:%20-116.35682061358298,%20%22ymin%22%20:%2033.57736122980378,%20%22xmax%22%20:%20-116.11014321490134,%20%22ymax%22%20:%2033.76479660485203%7D&callback=jQuery33106041300323957812_1649260209456&_=1649260209480](https://gis.la-quinta.org/arcgis/rest/services/BaseMap/Parcel/MapServer/1/query?&resultOffset=0&resultRecordCount=500&returnGeometry=true&outSR=4326&f=pbf&outFields=*&geometryType=esriGeometryEnvelope&geometry=%7B%22spatialReference%22:%7B%22wkid%22:4326%7D,%20%22xmin%22%20:%20-116.35682061358298,%20%22ymin%22%20:%2033.57736122980378,%20%22xmax%22%20:%20-116.11014321490134,%20%22ymax%22%20:%2033.76479660485203%7D&callback=jQuery33106041300323957812_1649260209456&_=1649260209480)

<img width="1657" alt="pbf300" src="https://user-images.githubusercontent.com/419582/162019669-151aa977-5b5b-4525-ac8d-499ce79196f6.png">

**Comment by rowanwins** [comment]
Hi @hoogw 

MapService query endpoints can have pbf support, apparently from 10.7.1 , although I suspect it might need to be enabled when a layer is published.
You can inspect if there is an entry in the `supportedQueryFormats` list for `pbf` at the root of MapService

For more details
https://developers.arcgis.com/rest/services-reference/enterprise/query-map-service-layer-.htm

This issue might be better posted in https://github.com/rowanwins/mapbox-gl-arcgis-featureserver if there is something particular going on. (Noting I was unable to access the service above)
